### ISSUE TITLE
(BUG renetik-android VERSION 1.0.2 )  The application crashes when i click on (REQUEST OF JSON ...) OPTION )

### ISSUE THREAD

**Issue by friendsmobile** [rene-dohan/renetik-library-android#1]
# Project Information

* Repository:  https://github.com/rene-dohan/renetik-android
* Project Name: renetik-android
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/rene-dohan/renetik-android/releases

# Expected behavior

after opening the application when  I click on  (REQUEST OF JSON ...) OPTION ) the Application should not be crash 

# Actual behavior

The application crashes when i click on (REQUEST OF JSON ...) OPTION )

#### How to reproduce

* [Download ](https://github.com/rene-dohan/renetik-android/releases)the application
*  open the application 
* click on (REQUEST OF JSON ...) OPTION )
* Note the Error

* Browser/App version:  VERSION 1.0.2
* Operating system: 6.0

#### Recording Of The Bug

![20190724_162749](https://user-images.githubusercontent.com/51118734/61790422-fca2ba00-adcb-11e9-95b8-4fcd338dfd3d.gif)

#### Logcat

<pre><code>D/AndroidRuntime(30227): Shutting down VM

E/AndroidRuntime(30227): FATAL EXCEPTION: main

E/AndroidRuntime(30227): Process: renetik.android.sample, PID: 30227

E/AndroidRuntime(30227): java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

E/AndroidRuntime(30227): 	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:302)

E/AndroidRuntime(30227): 	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:552)

E/AndroidRuntime(30227): 	at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:190)

E/AndroidRuntime(30227): 	at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:373)

E/AndroidRuntime(30227): 	at com.crashlytics.android.Crashlytics.log(Crashlytics.java:232)

E/AndroidRuntime(30227): 	at renetik.android.crashlitics.CrashlyticsLogger.info(CrashlyticsLogger.kt:42)

E/AndroidRuntime(30227): 	at renetik.android.logging.CSLog.logInfo(CSLog.kt:27)

E/AndroidRuntime(30227): 	at renetik.android.client.okhttp3.CSOkHttpClientKt.get(CSOkHttpClient.kt:83)

E/AndroidRuntime(30227): 	at renetik.android.client.okhttp3.CSOkHttpClientKt.get(CSOkHttpClient.kt:76)

E/AndroidRuntime(30227): 	at renetik.android.client.okhttp3.CSOkHttpClientKt.get(CSOkHttpClient.kt:74)

E/AndroidRuntime(30227): 	at renetik.android.client.okhttp3.CSOkHttpClientKt.get$default(CSOkHttpClient.kt:74)

E/AndroidRuntime(30227): 	at renetik.android.sample.model.SampleServer.ping(SampleServer.kt:33)

E/AndroidRuntime(30227): 	at renetik.android.client.request.CSPingMultiResponse.<init>(CSPing.kt:25)

E/AndroidRuntime(30227): 	at renetik.android.client.request.CSPingMultiResponse.<init>(CSPing.kt:21)

E/AndroidRuntime(30227): 	at renetik.android.client.request.CSPingRequest$1.invoke(CSPing.kt:12)

E/AndroidRuntime(30227): 	at renetik.android.client.request.CSPingRequest$1.invoke(CSPing.kt:11)

E/AndroidRuntime(30227): 	at renetik.android.client.request.CSRequest.send(CSRequest.kt:24)

E/AndroidRuntime(30227): 	at renetik.android.framework.extensions.CSRequest_DialogKt.sendWithProgress(CSRequest+Dialog.kt:11)

E/AndroidRuntime(30227): 	at renetik.android.framework.extensions.CSRequest_DialogKt.send(CSRequest+Dialog.kt:8)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.request.SamplePageListController$listController$2.invoke(SamplePageListController.kt:36)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.request.SamplePageListController$listController$2.invoke(SamplePageListController.kt:30)

E/AndroidRuntime(30227): 	at renetik.android.listview.request.CSRequestListController.reload(CSRequestListController.kt:26)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.request.SamplePageListController.onViewShowingFirstTime(SamplePageListController.kt:54)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.onViewShowing(CSViewController.kt:300)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.onViewVisibilityChanged(CSViewController.kt:288)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.updateVisibilityChanged(CSViewController.kt:272)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController$initialize$21.invoke(CSViewController.kt:208)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController$initialize$21.invoke(CSViewController.kt:32)

E/AndroidRuntime(30227): 	at renetik.android.java.event.CSEventKt$execute$1.invoke(CSEvent.kt:10)

E/AndroidRuntime(30227): 	at renetik.android.java.event.CSEventKt$execute$1.invoke(CSEvent.kt)

E/AndroidRuntime(30227): 	at renetik.android.java.event.CSEventImpl$EventRegistrationImpl.onEvent(CSEventImpl.kt:56)

E/AndroidRuntime(30227): 	at renetik.android.java.event.CSEventImpl.fire(CSEventImpl.kt:27)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.onViewVisibilityChanged(CSViewController.kt:295)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.updateVisibilityChanged(CSViewController.kt:272)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.onResume(CSViewController.kt:132)

E/AndroidRuntime(30227): 	at renetik.android.controller.base.CSViewController.initialize(CSViewController.kt:176)

E/AndroidRuntime(30227): 	at renetik.android.controller.common.CSNavigationController.push(CSNavigationController.kt:36)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.SampleNavigationActivityKt.push(SampleNavigationActivity.kt:12)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.SampleMainController$6.invoke(SampleMainController.kt:38)

E/AndroidRuntime(30227): 	at renetik.android.sample.view.SampleMainController$6.invoke(SampleMainController.kt:25)

E/AndroidRuntime(30227): 	at renetik.android.view.extensions.View_CSExtensionKt$onClick$$inlined$apply$lambda$1.onClick(View+CSExtension.kt:82)

E/AndroidRuntime(30227): 	at android.view.View.performClick(View.java:5076)

E/AndroidRuntime(30227): 	at android.view.View$PerformClick.run(View.java:20279)

E/AndroidRuntime(30227): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(30227): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(30227): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(30227): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(30227): 	at java.lang.reflect.Method.invoke(Native Met
</code></pre>

**Comment by rene-dohan** [comment]
Yeah Fabric was not initialised.. hm... sorry lib not maintained anymore for public use.
