### ISSUE TITLE
(BUG renetik-android VERSION 1.0.2 )  The Application crashes when i try to change the theme 

### ISSUE THREAD

**Issue by friendsmobile** [rene-dohan/renetik-library-android#2]
# Project Information

* Repository:  https://github.com/rene-dohan/renetik-android
* Project Name: renetik-android
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/rene-dohan/renetik-android/releases

# Expected behavior

When I try to change an existing theme, the theme should change

# Actual behavior

 The Application crashes when I try to change the theme 

#### How to reproduce

* [Download ](https://github.com/rene-dohan/renetik-android/releases)the application
*   open the application 
* At the top Right side click on Theme Chooser option 
* after Selected   your favorite theme click on Apply Selected Theme option
* Note the Error

* Browser/App version: VERSION 1.0.2
* Operating system: 6.0

#### Recording Of The Bug

![20190724_163947](https://user-images.githubusercontent.com/51118734/61790957-6f606500-adcd-11e9-86c4-6e4081384429.gif)

#### Logcat

<pre><code>D/AndroidRuntime(31796): Shutting down VM

E/AndroidRuntime(31796): FATAL EXCEPTION: main

E/AndroidRuntime(31796): Process: renetik.android.sample, PID: 31796

E/AndroidRuntime(31796): java.lang.RuntimeException: Unable to destroy activity {renetik.android.sample/renetik.android.sample.view.SampleNavigationActivity}: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

E/AndroidRuntime(31796): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4137)

E/AndroidRuntime(31796): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4155)

E/AndroidRuntime(31796): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4355)

E/AndroidRuntime(31796): 	at android.app.ActivityThread.access$1000(ActivityThread.java:177)

E/AndroidRuntime(31796): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)

E/AndroidRuntime(31796): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(31796): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(31796): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(31796): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(31796): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(31796): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(31796): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(31796): Caused by: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

E/AndroidRuntime(31796): 	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:302)

E/AndroidRuntime(31796): 	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:552)

E/AndroidRuntime(31796): 	at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:190)

E/AndroidRuntime(31796): 	at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:373)

E/AndroidRuntime(31796): 	at com.crashlytics.android.Crashlytics.log(Crashlytics.java:232)

E/AndroidRuntime(31796): 	at renetik.android.crashlitics.CrashlyticsLogger.warn(CrashlyticsLogger.kt:68)

E/AndroidRuntime(31796): 	at renetik.android.logging.CSLog.logWarn(CSLog.kt:18)

E/AndroidRuntime(31796): 	at renetik.android.java.common.TryAndKt.tryAndWarn(TryAnd.kt:14)

E/AndroidRuntime(31796): 	at renetik.android.java.common.TryAndKt.tryAndWarn(TryAnd.kt:20)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroyUnbindDrawables(CSActivity.kt:81)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroyUnbindDrawables(CSActivity.kt:80)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroyUnbindDrawables(CSActivity.kt:80)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroyUnbindDrawables(CSActivity.kt:80)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroyUnbindDrawables(CSActivity.kt:80)

E/AndroidRuntime(31796): 	at renetik.android.controller.base.CSActivity.onDestroy(CSActivity.kt:71)

E/AndroidRuntime(31796): 	at android.app.Activity.performDestroy(Activity.java:6418)

E/AndroidRuntime(31796): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)

E/AndroidRuntime(31796): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4124)

E/AndroidRuntime(31796): 	... 11 more
</code></pre>

**Comment by renetik-software** [comment]
Wau sorry I totally forgot this issue tracker . this repository is used extensively as my library for software development projects but I have no time to make it for other people. It is available as it is.. I cannot maintain sample projects and docs at all no time and money I need to work on apps...
